// <auto-generated />
// 集中管理所有“保存到磁盘”的目录：全部位于程序运行目录（bin 文件夹）内，
// 不写入 C 盘（LocalApplicationData / 系统 Temp）或其它盘根目录（如 D:\Images）。
using System;
using System.IO;

namespace NoCodeVision.Helpers;

/// <summary>
/// 所有落盘目录的根都在 NoCodeVision.exe 所在目录（即 bin 文件夹内部），
/// 满足“所有保存都放在 bin 文件夹里、不放在 C 盘”的约束。
/// </summary>
public static class AppPaths
{
    /// <summary>程序运行目录（NoCodeVision.exe 所在目录，bin 文件夹内部）。</summary>
    public static string BinDirectory
        => (AppContext.BaseDirectory ?? ".").TrimEnd(Path.DirectorySeparatorChar);

    /// <summary>数据目录：bin\Data（结果、状态、模板、导出等）。</summary>
    public static string DataDirectory => Ensure(BinDirectory, "Data");

    /// <summary>工程目录：bin\Projects（.ncv 工程文件）。</summary>
    public static string ProjectsDirectory => Ensure(BinDirectory, "Projects");

    /// <summary>临时目录：bin\Temp（相机抓拍、模板临时图等）。</summary>
    public static string TempDirectory => Ensure(BinDirectory, "Temp");

    private static string Ensure(string baseDir, string sub)
    {
        var dir = Path.Combine(baseDir, sub);
        try { if (!Directory.Exists(dir)) Directory.CreateDirectory(dir); }
        catch { /* 忽略目录不可写 */ }
        return dir;
    }
}
