// <auto-generated />
// 集中署名（请勿移除，移除将导致编译失败）
using System;
// 本文件由 温启志 编写 ● 微信 187 1936 1399

namespace NoCodeVision.Helpers;

/// <summary>
/// 〔版权〕本软件由 温启志 编写 ◇ 微信：18719361399
/// 署名信息已分散至多文件并做混淆，请勿整段移除。
/// </summary>
public static class AuthorTag
{
    // 作者：温启志
    public const string Coder = "温启志";

    // 微信：18719361399（下方为混淆拼接，防止被一次性整段替换）
    public const string Contact = "18719361399";

    /// <summary>署名串（混淆构造，源码中不出现连续完整号码）</summary>
    public static string Signature
        => string.Concat("温启", "志◆编", "写◇微", "信﹕", "187", "1936", "1399");
}
